Adding new items 01.09.2026-10:44:53

diff --git a/BackupBashScript/backupscript b/BackupBashScript/backupscript
--- a/BackupBashScript/backupscript
+++ b/BackupBashScript/backupscript
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+if [[ -z $1 ]]; then
+    echo "[$DATENOW][$TIMENOW] Don't forget to add your directory as argument! ex: bash newscript myphotos"
+    exit 1
+fi
 
 TIMENOW="$(date +'%H:%M:%S')"
 DATENOW="$(date +'%d.%m.%Y')"
@@ -10,43 +14,33 @@ SRCDIR="$(
     find ~ -type d -name "$1" -not -path "/home/$USER/.local/share/Thrash/*" | head -n 1
 )"
 
-DESTDIR="/home/$USER/Desktop/DevOpsProjects/BackupBashScript/$1 [$DATENOW][$TIMENOW]"
+DESTDIR="/home/$USER/Desktop/DevOpsProjects/BackupBashScript"
 
-if [[ -z $1 ]]; then
-    echo "[$DATENOW][$TIMENOW] Don't forget to add your directory as argument! ex: bash newscript myphotos"
-    exit 1
-fi
 
 if [[ -n $SRCDIR ]]; then
     
     echo "[$DATENOW][$TIMENOW] Found directory $1!"
     mkdir -p "$DESTDIR"
-    cp -r "$SRCDIR"/. "$DESTDIR"
-    if [ $? -eq 1 ]; then # Checking if copy command went well
-        echo "[$DATENOW][$TIMENOW] ERROR! Cannot copy files from source directory to backup directory"
-    else 
+    cp -r "$SRCDIR" "$DESTDIR/$1 [$DATENOW][$TIMENOW]"
+    if [ $? -eq 0 ]; then # Checking if copy command went well
         echo "[$DATENOW][$TIMENOW] Files copied succesfully!"
+    else 
+        echo "[$DATENOW][$TIMENOW] ERROR! Cannot copy files from source directory to backup directory"
     fi
 
-    # Github commands
-    # Supposed we are logged in with git and also we already set up the repo
-    # git init ...
-    # git branch -M main
-    # git remote add origin $GITREPO
-
-    # cd $DESTDIR || exit 1
+    cd "$DESTDIR" || exit 1
     
-    # git add .
-    # git commit -m "$(read)"
-    # git push origin main
+    git add "$DESTDIR/."
+    git commit -m "Adding new items $DATENOW-$TIMENOW"
+    git branch -M master
+    git push origin master
 
-    # if [ $? -eq 1 ]; then 
-    #     echo "[$DATENOW][$TIMENOW] ERROR! Github PUSH failed!"
-    # else
-    #     echo "[$DATENOW][$TIMENOW] Backup PUSHED to Github succesfully!"
-    # fi
+    if [ $? -eq 0 ]; then 
+        echo "[$DATENOW][$TIMENOW] Backup PUSHED to Github succesfully!"
+    else
+        echo "[$DATENOW][$TIMENOW] ERROR! Github PUSH failed!"
+    fi
 
 else
     echo "[$DATENOW][$TIMENOW] Directory NOT FOUND! Check for misstyping..."
 fi
-
